export default {
    "ABOUT REPICEA": "ABOUT REPICEA",
    "COMPANY INTRODUCTION": "COMPANY INTRODUCTION",
    "desc1_1": "Wuxi Revivingpicea Machinery Technology Co., Ltd. is a leading provider of cutting-edge solutions for heat exchange systems. We specialize in offering corrosion protection solutions for harsh environments. Our core product line includes glass lined shell-and-tube heat exchangers, silicon carbide shell-and-tube heat exchangers, and high-boron-silicate glass shell-and-tube heat exchangers. These innovative solutions provide exceptional corrosion resistance, high-temperature durability, and high-pressure capabilities. They serve as a superior choice to traditional metal(such as stainless steel, carbon steel, or alloys like titanium, nickel, or copper) heat exchangers, graphite heat exchangers, and other susceptible types.",
    "desc1_2": "Are you tired of dealing with corrosion, high temperature, and high pressure issues commonly faced with traditional metal heat exchangers, graphite heat exchangers, and other types? Look no further! Choosing us is the right decision. Revivingpicea is a highly reputable manufacturer specializing in shell and tube heat exchangers, providing the most professional solutions in the industry.",
    "desc2_1": "As an example, our glass lined shell-and-tube heat exchanger incorporates steel-clad PFA tubeplates and heat exchange tubes to eliminate the inherent cracking tendency of enamel. This design offers high thermal conductivity, durability, corrosion resistance, and improved sealing performance, effectively addressing issues commonly found in traditional enamel glass-tube heat exchangers. Additionally, our silicon carbide shell-and-tube heat exchanger provides excellent thermal conductivity, durability, corrosion resistance, and enhanced sealing performance. Furthermore, our high-boron-silicate glass shell and tube heat exchanger is specifically designed for applications requiring high temperatures and low thermal expansion.",
    "desc2_2": "Our dedicated team consists of 20 employees, including 5 technical experts and 5 sales consultants. With an annual production value of 40 million yuan for shell and tube heat exchangers, we are committed to delivering the highest level of performance, quality reputation, and service to all our customers. Our products have been widely utilized in thousands of large and medium-sized chemical production enterprises, earning praise for their reliable quality and efficient service.",
    "desc2_3": "If you are in need of advanced solutions for heat exchange systems in challenging environments, we encourage you to reach out to us without delay. Contact us today to discover more about our comprehensive range of products and services. We eagerly await the opportunity to collaborate with you and help you achieve your objectives.",
    "desc3_1": "We are proud to provide services to a diverse range of industries within the chemical sector in China. Our expertise caters to the food and pharmaceutical intermediate industries, where quality and safety are of utmost importance. We also serve the dye intermediate industry, focusing on precision and efficiency. Our commitment extends to the rapidly growing new energy industry as well. We have established strong partnerships with well-known companies such as Jinhe Industrial Group, a prominent player in the food additive production industry, and Lvxigroup, one of China's most competitive chemical companies. Additionally, we are privileged to serve esteemed clients such as Jihua Group, a world-renowned Sino-German joint venture known for producing dye intermediates, and Harbin Pharmaceutical Group, a leading pharmaceutical enterprise recognized for its dedication to quality and innovation. Furthermore, we provide our services to Gansu Yinguang Juyinhua Chemical Co, Ltd, a subsidiary of China Ordnance Industry Group, and many other esteemed companies in the industry.",
    "desc3_2": "We take great pride in our products, which have garnered extensive acclaim for their dependable quality and efficient service, showcasing our steadfast dedication to excellence. At the core of our philosophy lies trust and serving the needs of our customers. Our unwavering goal is to deliver outstanding performance, top-tier quality, an impeccable reputation, and considerate service, thereby earning the valuable trust and praise of our esteemed clientele.",
    "desc3_3": "Driven by a pioneering spirit, we constantly strive to enhance our technical capabilities and strengthen our customer relationships. Our unwavering commitment is to wholeheartedly serve our customers and nurture the enduring bonds we have forged over the years. We deeply value their continued support and eagerly anticipate our shared growth and success in the future.",
    "desc3_4": "With a deep understanding of the distinct requirements and complexities of every industry, we offer tailor-made solutions that surpass our customers' expectations. Our unwavering dedication to excellence and service, coupled with our technical proficiency and solid customer partnerships, position us as a trusted leader in the chemical industry. As we move forward, we eagerly anticipate the opportunity to consistently deliver top-notch services and support to these vital sectors for years to come.",
}
